name: "Increase actions and sources versions"
description: "Increase actions and sources versions"
inputs:
  base_commit:
    description: "Base commit SHA"
    required: true
  head_commit:
    description: "Head commit SHA"
    required: true
  all_files:
    description: "List of all files comming from changed_files step in check_version job github action workflow"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"